-- Table definitions
CREATE TABLE IF NOT EXISTS DEVICE (
    ID INTEGER PRIMARY KEY,
    TECHNICAL_NAME VARCHAR(255) UNIQUE,
    CUSTOM_NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS MEASUREMENT_TYPE (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS MEASUREMENT (
    ID INTEGER PRIMARY KEY,
    INSERTED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INSERTED_BY INTEGER,
    TYPE INTEGER,
    VALUE REAL,
    FOREIGN KEY(TYPE) REFERENCES MEASUREMENT_TYPE(ID),
    FOREIGN KEY(INSERTED_BY) REFERENCES DEVICE(ID)
);

-- Views
CREATE VIEW ALL_MEASUREMENTS AS
    SELECT strftime("%Y-%m-%dT%H:%M:%SZ", M.INSERTED_AT) AS "time"
    , M.VALUE AS "value"
    , T.NAME AS "type"
    , COALESCE(D.CUSTOM_NAME, D.TECHNICAL_NAME) AS "metric"
    FROM MEASUREMENT M
    JOIN DEVICE D ON M.INSERTED_BY = D.ID
    JOIN MEASUREMENT_TYPE T ON M.TYPE = T.ID
    ;

-- Indizes
CREATE INDEX IF NOT EXISTS XMEASUREMENT1 ON MEASUREMENT(ID);
CREATE INDEX IF NOT EXISTS XMEASUREMENT2 ON MEASUREMENT(INSERTED_AT, TYPE);
CREATE INDEX IF NOT EXISTS XMEASUREMENTTYPE1 ON MEASUREMENT_TYPE(ID);
CREATE INDEX IF NOT EXISTS XDEVICE1 ON DEVICE(ID);

-- Static data load
INSERT INTO MEASUREMENT_TYPE(NAME) VALUES('temperature');
INSERT INTO MEASUREMENT_TYPE(NAME) VALUES('humidity');
INSERT INTO MEASUREMENT_TYPE(NAME) VALUES('light');
INSERT INTO MEASUREMENT_TYPE(NAME) VALUES('co2');